const data = [
  {
    title: "Real Estate",
    des: "A platform to browse through various real estate listings.",
    img: "./pic13.png",
    technologies: ["Mongoo", "Express", "React", "Node", "Typescript"],
    bg: "#171700",
    code: "https://github.com/yusufobr/mern-estate",
    live: "https://mern-estate-1sq7.onrender.com/",
  },
  {
    title: "Stripe Nike Store",
    des: "Integrating Stripe Payment Gateway in an Eccomerce Website.",
    img: "./pic15.png",
    technologies: ["Stripe", "Node", "Express", "React", "Redux"],
    bg: "#565a79",
    code: "https://github.com/yusufobr/Stripe-Integration-Nike-Store",
  },
  {
    title: "Plate App",
    des: "Mobile App to order food.",
    img: "./pic10.png",
    technologies: ["React", "Redux", "Tailwind"],
    bg: "#141216",
    live: "https://incredible-macaron-e74db4.netlify.app/",
  },
  {
    title: "Spotify",
    des: "Your Hub for Music Tracks and Tunes.",
    img: "./pic3.png",
    bg: "#0E1217",
    technologies: ["Javascript", "Tailwind", "Shazam Api", "Html"],
    code: "https://github.com/yusufobr/Spotify-API-Javascript-Capstone",
    live: "https://dancing-narwhal-576108.netlify.app/",
  },
  {
    title: "Lokap 2.0",
    des: "NFC business card startup.",
    img: "./pic11.png",
    technologies: ["React", "Tailwind"],
    bg: "#28282B",
    live: "https://astonishing-crumble-af591e.netlify.app/",
  },
  {
    title: "Chat-IO",
    des: "Real Time Chat Application. It allows multiple users to join chat rooms and communicate with each other in real-time.",
    img: "./pic16.png",
    technologies: ["React", "Socket.io", "Node", "Express"],
    bg: "#231200",
    code: "https://github.com/yusufobr/chat-io/",
  },
  {
    title: "Diseny Plus 2.0 ",
    des: "Display Trending Movies & TV Shows",
    img: "./pic7.jpg",
    technologies: ["React", "Tailwind", "REST Api"],
    code: "https://github.com/yusufobr/diseny-plus",
    live: "https://disenyplus.netlify.app/",
  },
  {
    title: "Crypto's",
    des: "Crypto Coin app details.",
    img: "./pic1.png",
    technologies: ["React", "Redux", "Tailwind", "ReChart.js"],
    bg: "#161B19",
    code: "https://github.com/yusufobr/crypto-data",
    live: "https://cryptoscoin.netlify.app/",
  },
  {
    title: "Agaplex SA",
    des: "Moroccan Foundry E-Commerce Website.",
    img: "./pic4.png",
    technologies: ["Wordpress", "Javascript", "PHP"],
    live: "https://www.agaplex.com/",
  },
  {
    title: "Weather App",
    des: "Weather app to check the real-time weather.",
    img: "./pic2.png",
    technologies: ["React", "REST Api"],
    bg: "#B56782",
    code: "https://github.com/yusufobr/weather-react",
    live: "https://magical-pithivier-03eaa5.netlify.app/",
  },
  {
    title: "Soccer App",
    des: "Provide information about the standings of different leagues.",
    img: "./pic5.png",
    technologies: ["React", "Redux", "REST Api", "Tailwind"],
    code: "https://github.com/yusufobr/weather-react",
    live: "https://soccer-live.netlify.app/",
  },
  {
    title: "Manage",
    des: "Attractive Responsive Landing Page using Tailwind Css",
    img: "./pic6.png",
    technologies: ["Html", "Tailwind", "Javascript"],
    bg: "#242d52",
    code: "https://github.com/yusufobr/manage-tailwindcss",
    live: "https://yusufobr.github.io/manage-tailwindcss/",
  },
  {
    title: "EX-INVESTOR",
    des: "Amateur investors seeking to gain inspiration and motivation from the success stories of seasoned investors.",
    img: "./pic12.png",
    technologies: ["Html", "Tailwind", "Javascript"],
    bg: "#EC5242",
    code: "https://github.com/yusufobr/conference-capstone",
    live: "https://yusufobr.github.io/conference-capstone/",
  },
  {
    title: "Wajibati",
    des: "Portfolio website to show Infos about the App.",
    img: "./pic9.png",
    technologies: ["Html", "Css", "Javascript"],
    bg: "#3c55f0",
    code: "https://github.com/yusufobr/ios",
    live: "https://yusufobr.github.io/ios/",
  },
  {
    title: "Leaderboard",
    des: "A leaderboard app to track Scores",
    img: "./pic8.jpg",
    technologies: ["Html", "Tailwind", "Javascript"],
    bg: "#1c0036",
    code: "https://github.com/yusufobr/Leaderboard",
    live: "https://polite-chebakia-a51660.netlify.app/",
  },
  {
    title: "Landing Page",
    des: "A responsive landing page using Tailwind Css.",
    img: "./pic14.png",
    technologies: ["Html", "Tailwind"],
    bg: "#212b33",
    live: "https://genuine-bienenstitch-107a1d.netlify.app/",
  },
];

export default data;
