const data = [
    {
        title: "Spotify",
        des: "Spotify musical track website.",
        img: "./pic3.png",
        bg: "#0E1217",
        technologies: ["Tailwind", "Javascript", "Html"],
        code: "https://github.com/yusufobr/Spotify-API-Javascript-Capstone",
        live: "https://dancing-narwhal-576108.netlify.app/",
    },
    {
        title: "Diseny Plus 2.0 ",
        des: "Display Trending Movies & TV Shows",
        img: "./pic7.jpg",
        code: "https://github.com/yusufobr/diseny-plus",
        live: "https://disenyplus.netlify.app/",
    },
    {
        title: "Crypto's",
        des: "Crypto Coin app details.",
        img: "./pic1.png",
        bg: "#161B19",
        code: "https://github.com/yusufobr/crypto-data",
        live: "https://profound-cendol-db4de9.netlify.app/",
    },
    {
        title: "Agaplex SA",
        des: "Moroccan Foundry E-Commerce Website.",
        img: "./pic4.png",
        technologies: ["Tailwind", "Javascript", "Html"],
        live: "https://www.agaplex.com/",
    },
    {
        title: "Weather App",
        des: "Weather app to check the real-time weather.",
        img: "./pic2.png",
        bg: "#B56782",
        code: "https://github.com/yusufobr/weather-react",
        live: "https://magical-pithivier-03eaa5.netlify.app/",
    },
    {
        title: "Soccer App",
        des: "Provide information about the standings of different leagues.",
        img: "./pic5.png",
        code: "https://github.com/yusufobr/weather-react",
        live: "https://soccer-live.netlify.app/",
    },
    {
        title: "Manage",
        des: "Attractive Responsive Landing Page using Tailwind Css",
        img: "./pic6.png",
        bg: "#242d52",
        code: "https://github.com/yusufobr/manage-tailwindcss",
        live: "https://yusufobr.github.io/manage-tailwindcss/",
    },
    {
        title: "Leaderboard",
        des: "A leaderboard app to truck Scores",
        img: "./pic8.jpg",
        bg: "#202020",
        code: "https://github.com/yusufobr/Leaderboard",
        live: "https://polite-chebakia-a51660.netlify.app/",
    },
];

export default data;
