const data = [


{
        title: "Plate App",
        des: "Mobile App to order food.",
        img: "./pic10.png",
        technologies: ["React", "Redux", "Tailwind"],
        bg: "#141216",
        live: "https://incredible-macaron-e74db4.netlify.app/",
    },    {
        title: "Spotify",
        des: "Your Hub for Music Tracks and Tunes.",
        img: "./pic3.png",
        bg: "#0E1217",
        technologies: ["Javascript", "Tailwind", "Shazam Api", "Html"],
        code: "https://github.com/yusufobr/Spotify-API-Javascript-Capstone",
        live: "https://dancing-narwhal-576108.netlify.app/",
    },
    {
        title: "Diseny Plus 2.0 ",
        des: "Display Trending Movies & TV Shows",
        img: "./pic7.jpg",
        technologies: ["React", "Tailwind", "REST Api"],
        code: "https://github.com/yusufobr/diseny-plus",
        live: "https://disenyplus.netlify.app/",
    },
    {
        title: "Crypto's",
        des: "Crypto Coin app details.",
        img: "./pic1.png",
        technologies: ["React", "Redux", "Tailwind", "ReChart.js"],
        bg: "#161B19",
        code: "https://github.com/yusufobr/crypto-data",
        live: "https://cryptoscoin.netlify.app/",
    },
    {
        title: "Agaplex SA",
        des: "Moroccan Foundry E-Commerce Website.",
        img: "./pic4.png",
        technologies: ["Wordpress", "Javascript", "PHP"],
        live: "https://www.agaplex.com/",
    },
    {
        title: "Weather App",
        des: "Weather app to check the real-time weather.",
        img: "./pic2.png",
        technologies: ["React", "REST Api"],
        bg: "#B56782",
        code: "https://github.com/yusufobr/weather-react",
        live: "https://magical-pithivier-03eaa5.netlify.app/",
    },
    {
        title: "Soccer App",
        des: "Provide information about the standings of different leagues.",
        img: "./pic5.png",
        technologies: ["React", "Redux", "REST Api" ,"Tailwind"],
        code: "https://github.com/yusufobr/weather-react",
        live: "https://soccer-live.netlify.app/",
    },
    {
        title: "Manage",
        des: "Attractive Responsive Landing Page using Tailwind Css",
        img: "./pic6.png",
        technologies: ["Html", "Tailwind", "Javascript"],
        bg: "#242d52",
        code: "https://github.com/yusufobr/manage-tailwindcss",
        live: "https://yusufobr.github.io/manage-tailwindcss/",
    },
    {
        title: "Wajibati",
        des: "Portfolio website to show Infos about the App.",
        img: "./pic9.png",
        technologies: ["Html", "Css", "Javascript"],
        bg: "#3c55f0",
        code: "https://github.com/yusufobr/ios",
        live: "https://yusufobr.github.io/ios/",
    },
    // {
    //     title: "Leaderboard",
    //     des: "A leaderboard app to track Scores",
    //     img: "./pic8.jpg",
    //     technologies: ["Html", "Tailwind", "Javascript"],
    //     bg: "#1c0036",
    //     code: "https://github.com/yusufobr/Leaderboard",
    //     live: "https://polite-chebakia-a51660.netlify.app/",
    // },
];

export default data;
